name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: 'Run verification'
              run: |
                  npm ci
                  npm run lint:pkg-json
                  npm run lint:js
