name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: |
                  npm ci
                  npm lint:pkg-json
                  npm lint:js
